### ISSUE TITLE
Address values in the dropdown not shown after you close the pop up and return to select address page.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/greengrainbowl#1]
**Describe the bug**
Address values in the dropdown not shown after you close the pop up and return to select address page.

**To Reproduce**
1. Go to 'https://greengrainbowl.com/#/cart'.
2. Click on 'ADD'.
3. Enter the address as 'porv'
4.Select the location 'Porvorim,Aradi Socorro,Goa,India' from the dropdown.
5.Click on the address on the product listing page.

**Expected behavior**
The address selected from the dropdown should be displayed in the textbox.

**Screenshots**
![location_display_1](https://user-images.githubusercontent.com/54023516/67096309-77198500-f1d5-11e9-8dff-3728a3b26b38.png)
![location_display_2](https://user-images.githubusercontent.com/54023516/67096385-b47e1280-f1d5-11e9-9571-5d9687c52073.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome ]
 - Version [Version 77.0.3865.90 ]

**Comment by sujitgawas19** [comment]
Search text entered will be cleared on opening the select location modal.

**Comment by larissa-c-d** [comment]
Issue Solved ,Testing done
