### ISSUE TITLE
If the Quantity of the item is increased the "To Pay" amount is not updated accordingly.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/greengrainbowl#10]
Describe the bug
If the Quantity of the item is increased the "To Pay" amount is not updated accordingly.

To Reproduce
1.Go to 'https://greengrainbowl.com'
2.Click on 'ADD.'
3.Set the address.
4.click on 'View Cart'
5.click on 'ADD'
6.See error

Expected behavior
If the Quantity of the item is increased the "To Pay" should be updated.

Screenshots
![cart_not_updated](https://user-images.githubusercontent.com/54023516/67100891-29554a80-f1de-11e9-85c1-efad45184732.png)

Desktop (please complete the following information):

OS: [Linux]
Browser [chrome]
Version [Version 77.0.3865.90]

**Comment by sujitgawas19** [comment]
Same as issue #8

**Comment by larissa-c-d** [comment]
When the cart page is open, clicks should be disabled on the product listing page.
