### ISSUE TITLE
order placed mail: Order id link does not redirect to valid cart

### ISSUE THREAD

**Issue by AkshataSail** [ajency/greengrainbowl#104]
![Screenshot 2019-12-10 at 12 55 52 PM](https://user-images.githubusercontent.com/47238092/70505095-237c4580-1b4d-11ea-9598-ddd147998620.png)
![Screenshot 2019-12-10 at 12 59 28 PM](https://user-images.githubusercontent.com/47238092/70505096-2414dc00-1b4d-11ea-8514-8cd92072f1de.png)

**Comment by verlekar-viraj** [comment]
Page is not yet complete.
@lateshK is working on it.

**Comment by AkshataSail** [comment]
Done.
