### ISSUE TITLE
User login : Validation is required for new user login

### ISSUE THREAD

**Issue by AkshataSail** [ajency/greengrainbowl#109]
1. Steps:
>Click on submit button without entering mobile number
Error: No validation message is displayed

2. Need to add validations for invalid numbers with digits more and less than 10 

![Screenshot 2019-12-10 at 3 36 06 PM](https://user-images.githubusercontent.com/47238092/70520116-110d0680-1b63-11ea-96f3-c6c3315f4734.png)

**Comment by TejalBandekar** [comment]
This issue still persist.

**Comment by TejalBandekar** [comment]
Fixed.
