### ISSUE TITLE
Mobile verification: Validation is required

### ISSUE THREAD

**Issue by AkshataSail** [ajency/greengrainbowl#110]
1. When Resend otp is clicked , otp input box must blank be again
2. On entering invalid otp , proper failure message must be displayed with a smaller font

![Screenshot 2019-12-10 at 3 41 54 PM](https://user-images.githubusercontent.com/47238092/70520560-c0e27400-1b63-11ea-9ad9-3a9a7abc4beb.png)

**Comment by AkshataSail** [comment]
3. Validation is required when 'verify otp' is clicked with no otp entered in box.
![Screenshot 2019-12-11 at 10 30 01 AM 2](https://user-images.githubusercontent.com/47238092/70592915-4a944f00-1c01-11ea-8abe-8c6c177c8cca.png)

**Comment by TejalBandekar** [comment]
This issue still persist 

> When Resend otp is clicked , otp input box must blank be again

**New issues** 

- There is no limit set while entering an otp. 
If otp is of 6 digits, then input of only 6 digits has to be allowed. 

- When a wrong otp is entered, a validation msg is displayed. Ideally, when a box is empty or resend is clicked validation msg shouldn't be displayed 
![image](https://user-images.githubusercontent.com/45193277/71059271-7925a300-2188-11ea-8638-0dcc0a203deb.png)

**Comment by TejalBandekar** [comment]
Fixed.
