### ISSUE TITLE
Total amount on payment gateway fails to update when the cart is updated in other tab

### ISSUE THREAD

**Issue by AkshataSail** [ajency/greengrainbowl#111]
Steps:
>TAB1-Go to greengrainbowl.com/oyo
>add item A, qty=3 to cart; check amount=300
>Duplicate the tab
>TAB2-update qty=2; check amount=200
>Go to TAB1- proceed with payment
Error: Amount is still shown as 300

Expected: amount must be 200

**Comment by TejalBandekar** [comment]
Fixed.
