### ISSUE TITLE
cart summary page:  Ui issue

### ISSUE THREAD

**Issue by AkshataSail** [ajency/greengrainbowl#118]
Mobile no must go to next line
![Screenshot 2019-12-11 at 11 47 27 AM](https://user-images.githubusercontent.com/47238092/70597328-170bf180-1c0e-11ea-8147-2fbf3cb48b09.png)

**Comment by AkshataSail** [comment]
Display of GGB logo on 'account details'  loader must be improved.
![Screenshot 2019-12-11 at 1 23 31 PM](https://user-images.githubusercontent.com/47238092/70602207-de721500-1c19-11ea-99e9-839750ef1d31.png)

**Comment by TejalBandekar** [comment]
Fixed.
