### ISSUE TITLE
Tracking order summary page link has some markup - 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/greengrainbowl#155]
**Describe the bug**
Tracking order summary page link has some markup - 

![image](https://user-images.githubusercontent.com/14803102/83014365-32dc4600-a03c-11ea-9291-41ffd208469a.png)

**Comment by rohan-morje** [comment]
Order summary page not loading

**Comment by lateshK** [comment]
![screenshot-greengrainbowl com-2020 05 28-12_35_03](https://user-images.githubusercontent.com/42994943/83109834-b69b3e80-a0df-11ea-9fe6-96389aba968f.png)
