### ISSUE TITLE
Mobile devices - Scrolling is not smooth on home page when user is redirected to homepage after placing the order

### ISSUE THREAD

**Issue by rohan-morje** [ajency/greengrainbowl#163]
**Describe the bug**
Scrolling is not smooth on home page when user is redirected to homepage after placing the order

**To Reproduce**
1. Go to 'ggb site
2. Place the order and complete the payment
3. Click on I WANT MORE, TAKE MR TO SHOP to continue 
4. User will navigate to home page
5. Scroll the homepage and observe the issue

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: one plus 6
 - OS:11
 - Browser chrome
 - Version 80

**Comment by nutank** [comment]
@rohan-morje can you add a video screenshare?

**Comment by lateshK** [comment]
@Vaibhavarolkar can you look into this.

**Comment by rohan-morje** [comment]
Attached video for reference
[VID-20200529-WA0007.zip](https://github.com/ajency/greengrainbowl/files/4700213/VID-20200529-WA0007.zip)
