### ISSUE TITLE
Mobile - New user - User is navigated to blank screen when user click on back button before entering the phone number

### ISSUE THREAD

**Issue by rohan-morje** [ajency/greengrainbowl#180]
**Describe the bug**
Mobile - New user - User is navigated to blank screen when user click on back button before entering the phone number

**To Reproduce**
1. Go to 'ggb
2. Add product to cart
3. click on proceed to checkout
4. do not enter phone number -> click onSubmit
click on back button twice and observe

**Expected behavior**
Blank screen should not display

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: one plus 6
 - OS:11
 - Browser chrome

**Comment by nutank** [comment]
@rohan-morje please close this ticket if you cant replicate.
