### ISSUE TITLE
Order summary was not displaying when payment mode selected was Pay Later and user is naviagted to 

### ISSUE THREAD

**Issue by rohan-morje** [ajency/greengrainbowl#189]
**Describe the bug**
Order summary was not displaying when payment mode selected was Pay Later

**To Reproduce**
1. Go to ggb site
2. Add product to cart
3. Select the payment mode as Pay later
4. Place the order

**Expected behavior**
Order summary should display

**Screenshots**
![image](https://user-images.githubusercontent.com/14803102/84357261-018a7b00-abe3-11ea-8ddf-167ecc3c6bd9.png)

**Desktop (please complete the following information):**
 - OS: windows 8
 - Browser chorme
 - Version 82

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/84382890-f5191900-ac08-11ea-984e-846993ae0980.png)

**Comment by lateshK** [comment]
Request raised by @nutank  to Razor pay to disable the payment option.
