### ISSUE TITLE
Mobile view: Day and slot details are not displaying in Order Summary which is received through SMS

### ISSUE THREAD

**Issue by rohan-morje** [ajency/greengrainbowl#197]
**Describe the bug**
Day and slot details are not displaying in Order Summary which is received through SMS

**To Reproduce**
1. Go to ggb site
2. Place the order by selecting order date as Wednesday and slot as Dinner and observe the Order Summary received via SMS 

**Expected behavior**
Day and slot details are not displaying in Order Summary which is received through SMS

**Screenshots**
![image](https://user-images.githubusercontent.com/14803102/84631782-935bf600-af0b-11ea-90ea-10379cc297af.png)

**Desktop (please complete the following information):**
 - OS: windows 8
 - Browser chrome
 - Version   82

**Smartphone (please complete the following information):**
 - Device: one pplus
 - OS: 10
 - Browser  chrome
 - Version 80

![image](https://user-images.githubusercontent.com/14803102/84631886-c1413a80-af0b-11ea-815e-778655f258e1.png)

**Comment by nutank** [comment]
@rohan-morje - can you check on other phone and see if it replicates?

**Comment by rohan-morje** [comment]
Displaying on latesh phone
