### ISSUE TITLE
Amount is not updated correctly is Order Summary page

### ISSUE THREAD

**Issue by rohan-morje** [ajency/greengrainbowl#198]
**Describe the bug**
Amount is not updated correctly is Order Summary page. 1 rupee is shown instead of 2 

**To Reproduce**
1. Go to ggb site
2. Add 1 product to cart with qty 1 and day: monday and slot : lunch
Add 1 more product to cart with qty 2 and day: wed and slot : dinner
3. PLace the order and observe the Order Sumamry page 

**Expected behavior**
Amount should correctly reflect

**Screenshots**

![image](https://user-images.githubusercontent.com/14803102/84642787-97434480-af1a-11ea-8011-faa0be8382f7.png)

![image](https://user-images.githubusercontent.com/14803102/84642924-c8bc1000-af1a-11ea-9e35-3aa9d4033daf.png)

**Smartphone (please complete the following information):**
 - Device: one plus 8
 - OS: 10
 - Browser chrome
 - Version 80

**Comment by nutank** [comment]
Not an issue. It is the original behaviour
