### ISSUE TITLE
Iphone - Garbage data is displayed when minimise the product quantity to 1 on your cart page

### ISSUE THREAD

**Issue by rohan-morje** [ajency/greengrainbowl#201]
**Describe the bug**
Iphone - Garbage text is displayed when minimise the product quantity to 1 on your cart page.
Undefined is not an object (evaluating en quantity ) is displayed

**To Reproduce**
1. Go to ggb site in iphone safari browser
2. Add product to cart
3.Navigate to Your cart page 
4. Increase thequantity of product to 3 by clicking on + icon
5. Decrease the quantity to 1 by clicking on - icon and observe

**Expected behavior**
Garbage data should not display

**Screenshots**

![image](https://user-images.githubusercontent.com/14803102/84653275-c497ee80-af2a-11ea-9e64-c8337cb7c6ec.png)

**Smartphone (please complete the following information):**
 - Device: iphone 8 plus
 - OS: ios  13.3
 - Browser safari

**Comment by lateshK** [comment]
@rohan-morje Was not able to replicate the issue
