### ISSUE TITLE
Iphone -  Sometimes Proceed to Payment button is not clickable

### ISSUE THREAD

**Issue by rohan-morje** [ajency/greengrainbowl#210]
**Describe the bug**
Iphone -  Sometimes Proceed to Payment button is not clickable

**To Reproduce**
1. Go to ggb site
2. Add product to cart
3. Navigate to your cart page and click on Proceed to Payment button

**Expected behavior**
Proceed to payment button should be clickable

**Screenshots**
![image](https://user-images.githubusercontent.com/14803102/84765829-6c75f080-afed-11ea-8421-a5ff534cdfb8.png)

**Smartphone (please complete the following information):**
 Device: 8 plus
OS: 13
Browser Safari

**Comment by lateshK** [comment]
This issue is related to shifting of the payment button.
