### ISSUE TITLE
iphone - UI issue related to Proceed to Payment button

### ISSUE THREAD

**Issue by rohan-morje** [ajency/greengrainbowl#211]
**Describe the bug**
 UI issue related to Proceed to Payment button
1) Position of Proceed to payment button is not proper
2) Proceed to Payment button displaying multiple times
3) Sometimes Proceed to Payment become invisible 

**To Reproduce**
1. Go to ggb site
2. Add product to cart
3. Navigate to your cart page and click on Proceed to Payment button

**Expected behavior**
UI should not be broken of Proceed to payment button 

**Screenshots**
![image](https://user-images.githubusercontent.com/14803102/84765829-6c75f080-afed-11ea-8421-a5ff534cdfb8.png)

![image](https://user-images.githubusercontent.com/14803102/84766506-90860180-afee-11ea-8468-f5ba142a9991.png)

**Smartphone (please complete the following information):**
 Device: 8 plus
OS: 13
Browser Safari

**Comment by nutank** [comment]
@Vaibhavarolkar similar issue happens for buttons on other pages - #199, #200 , #203 , #204

**Comment by rohan-morje** [comment]
One overlapping of Proceed to Payment issue exist
