### ISSUE TITLE
Current location cannot be fetched.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/greengrainbowl#27]
**Describe the bug**
Current location cannot be fetched.

**To Reproduce**
1. Go to 'http://greengrainbowl-com.digitaldwarve.staging.wpengine.com/'
2. Click on 'location icon'
3.Turn on the location setting. 
4.Click on 'Use current location.'
5. See error.

**Expected behavior**
Location should be fetched on click of 'Use current location'.

**Screenshots**
![image](https://user-images.githubusercontent.com/54023516/67652568-7cac6300-f96b-11e9-8229-c0ed42b71ac8.png)

**Smartphone (please complete the following information):**
Device: [Sony Xperia]
OS: [Android 8.0.0]
Browser [chrome]
Version [77.0.3865.116]

**Comment by sujitgawas19** [comment]
Test this feature on production server - https://greengrainbowl.com/

**Comment by larissa-c-d** [comment]
Since the SSL  on the Staging server was not fixed this feature has been tested on the production server which had an SSL.
Current location is fetched.
