### ISSUE TITLE
'Resend OTP' sends back the same OTP.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/greengrainbowl#40]
**Describe the bug**
'Resend OTP' sends back the same OTP.

**To Reproduce**
1. Go to 'http://greengrainbowl-com.digitaldwarve.staging.wpengine.com/'
2. Click on 'Location ' icon
3. Click on 'Click on edit ' icon
4. Click on 'Sign In'
5.Enter the mobile number.
6.Click on Resend OTP.
7.See the error

**Expected behavior**
A new OTP should be send on clicking Resend OTP.

**Screenshots**
![image](https://user-images.githubusercontent.com/54023516/67944584-cb275f00-fc02-11e9-8f1d-b62678d79b47.png)

**Desktop (please complete the following information):**
OS: [Linux]
Browser [ chrome]
Version [77.0.3865.90]

**Smartphone (please complete the following information):**
 Device: [Sony Xperia]
OS: [Android 8.0.0]
Browser [chrome]
Version [77.0.3865.116]

**Comment by verlekar-viraj** [comment]
Resend OTP is meant to send the same OTP again
