### ISSUE TITLE
item Quantity does not  change accordingly when an item is added to cart.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/greengrainbowl#8]
**Describe the bug**
If an item has been successfully added to the cart then  the item Quantity does not  change accordingly.

**To Reproduce**
1. Go to 'https://greengrainbowl.com'
2. Click on 'ADD.'
3. Set the address.
4.click on 'View Cart'
5.click on 'ADD'
6. See error

**Expected behavior**
verify that if an item has been successfully added to the cart then  the item Quantity should change accordingly.

**Screenshots**

![image](https://user-images.githubusercontent.com/54023516/67099847-4426bf80-f1dc-11e9-8240-a4ac3c648991.png)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [chrome]
 - Version [Version 77.0.3865.90]

**Comment by sujitgawas19** [comment]
This happens when we have the cart open and add something from products page.
When the cart is open there will be an overlay on  products page, so clicks will be allowed on product page until the cart is closed.

**Comment by larissa-c-d** [comment]
When the cart page is open, clicks should be disabled on the product listing page.
