### ISSUE TITLE
If an item is successfully added to cart the total cart amount is not updated.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/greengrainbowl#9]
Describe the bug
If an item is successfully added to cart the total cart amount is not updated.

To Reproduce

Go to 'https://greengrainbowl.com'
Click on 'ADD.'
Set the address.
4.click on 'View Cart'
4.click on 'ADD'
See error

Expected behavior
If an item is successfully added to cart the total cart amount should be updated.

Screenshots
![cart_not_updated](https://user-images.githubusercontent.com/54023516/67100475-5b19e180-f1dd-11e9-81f7-3f4fdd391883.png)

Desktop (please complete the following information):

OS: [Linux]
Browser [chrome]
Version [Version 77.0.3865.90]

**Comment by sujitgawas19** [comment]
Same as issue #8

**Comment by larissa-c-d** [comment]
When the cart page is open, clicks should be disabled on the product listing page.
