### ISSUE TITLE
Items are  displayed multiple times on the product listing page.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/greengrainbowl#91]
**Describe the bug**
Items are  displayed multiple times on the product listing page.

**To Reproduce**
1. Go to 'http://greengrainbowl-com.digitaldwarve.staging.wpengine.com/'
2. See error

**Expected behavior**
Same product should not be listed multiple times.

**Screenshots**
![image](https://user-images.githubusercontent.com/54023516/69026394-b283bb00-09f0-11ea-8cc9-38f308f20a14.png)

**Desktop (please complete the following information):**
-OS: [Linux]
-Browser [chrome]
-Version 77.0.3865.90

**Comment by verlekar-viraj** [comment]
Dummy data added for testing. Not displayed multiple times
