### ISSUE TITLE
Item count is displayed on the product listing page, when the cart is empty.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/greengrainbowl#93]
**Describe the bug**
On clearing the cache cart is emptied and the change is not reflected on the  product listing page .

**To Reproduce**
1. Go to 'http://greengrainbowl-com.digitaldwarve.staging.wpengine.com/'
2. Add items to cart.
3. Clear the cache.
4. Go to 'http://greengrainbowl-com.digitaldwarve.staging.wpengine.com/'
5.Click on view cart.
6.See the error.

**Expected behavior**
If the cart is empty,the item count should be reflected on the product listing page..

**Screenshots**
![image](https://user-images.githubusercontent.com/54023516/69028760-01cde980-09f9-11ea-9069-c5831370f56f.png)
![image](https://user-images.githubusercontent.com/54023516/69028762-0397ad00-09f9-11ea-96e1-5e7ed8afffe7.png)
![sync when cart is empty 1](https://user-images.githubusercontent.com/54023516/69029775-e3b5b880-09fb-11ea-9f9f-fc17fd8cf788.png)
![sync when cart is empty](https://user-images.githubusercontent.com/54023516/69029779-e7e1d600-09fb-11ea-8091-6749bf8ea233.png)

**Desktop (please complete the following information):**
-OS: [Linux]
-Browser [chrome]
-Version 77.0.3865.90

**Comment by verlekar-viraj** [comment]
If application cache is cleared from dev console, changes will reflect on refresh
